### ISSUE TITLE
Dollar sign fails.

### ISSUE THREAD

**Issue by sdegutis** [fhd/clostache#50]
The test named `test-render-with-dollar-sign` is currently failing on version 1.4.0

~~~clojure
(= "Hello, $Felix!" (render "Hello, {{! This is a comment.}}{{name}}!"
                            {:name "$Felix"}))
; => false

(render "Hello, {{! This is a comment.}}{{name}}!"
        {:name "$Felix"})
; => "Hello, \\$Felix!"
~~~

**Comment by fotoetienne** [comment]
This issue is resolved in my fork of clostache: https://github.com/fotoetienne/cljstache

**Comment by fhd** [comment]
Should have been fixed by https://github.com/fhd/clostache/commit/a30c5a7db521cfc31c1b63e8df4398a7c677d574, same as #43. Please reopen if you disagree.

**Comment by sdegutis** [comment]
@fhd 👍
